### ISSUE TITLE
Error: Killedting to dataframe...

### ISSUE THREAD

**Issue by DrArtist2027** [OxWearables/stepcount#128]
I followed the tutorial, but when I run the stepcount command `stepcount 1000308_90001_0_0.cwa`, I keep getting the following message and no output file. I'm confused as to what went wrong.
The error message is as follows:
```
Reading file... Done! (43.80s)
Killedting to dataframe...
```
I would appreciate it if someone could give me some help.

**Comment by chanshing** [comment]
Hi @DrArtist2027 this typically happens when your machine ran out of memory. How big is the file you're trying to process (how many days of recording) and how much RAM does your machine have?
