### ISSUE TITLE
Attribute error not allowing creation of summary/adjusted files

### ISSUE THREAD

**Issue by smallsr** [OxWearables/stepcount#22]
In some participants (not all, seemingly those with significant amounts of non-wear), an attribute error is flagged when summarising data.

daily_avg = daily.mean().round()
AttributeError: 'float' object has no attribute 'round'.

![image](https://user-images.githubusercontent.com/45289908/236504358-5bea2d4f-3419-49d5-9f8b-19d41a48b8de.png)

**Comment by smallsr** [comment]
These files are created before the error, but the others (DailyStepsAdjusted, DailyWalkAdjusted, HourlyStepsAdjusted, *-Info.json, *-Steps.csv ) are not.

![image](https://user-images.githubusercontent.com/45289908/236504781-ba04ea75-16ef-472b-8cc8-cfd787181eaa.png)

**Comment by chanshing** [comment]
Thanks @smallsr 
Can you share the input file to reproduce this error?

**Comment by smallsr** [comment]
Link on rescomp sent via Teams @chanshing

**Comment by chanshing** [comment]
Hi @smallsr This is fixed now in v2.1.3
