### ISSUE TITLE
ValueError: cannot reindex a non-unique index with a method or limit

### ISSUE THREAD

**Issue by chriszal** [OxWearables/stepcount#25]
Im trying to get an output using the below csv but i get an error.
source.csv:
time,x,y,z
2022-01-27 12:21:52.123000,2.9240294,4.808078,8.586046
2022-01-27 12:21:52.144000,2.9706893,4.9196434,8.013563
2022-01-27 12:21:52.164000,3.728915,5.374579,7.7967134
2022-01-27 12:21:52.184000,3.4977086,4.6226344,7.84128
2022-01-27 12:21:52.204000,3.3768709,3.8751762,8.340483
2022-01-27 12:21:52.225000,3.789932,4.10399,8.355139

error:

> Getting stationary points... Done! (0.03s)
> /home/chris/influx-testing/.venv/lib/python3.8/site-packages/actipy/processing.py:195: UserWarning: Skipping calibration: Insufficient stationary samples
>   warnings.warn(f"Skipping calibration: Insufficient stationary samples")
> Gravity calibration... Done! (0.01s)
> Nonwear detection... Done! (0.03s)
> Traceback (most recent call last):
>   File "/home/chris/influx-testing/.venv/bin/stepcount", line 8, in <module>
>     sys.exit(main())
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/stepcount/stepcount.py", line 45, in main
>     data, info = read(args.filepath, resample_hz)
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/stepcount/stepcount.py", line 276, in read
>     data, info = actipy.process(
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/actipy/reader.py", line 130, in process
>     data, info_resample = P.resample(data, resample_hz)
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/actipy/processing.py", line 42, in resample
>     data = data.reindex(t, method='nearest', tolerance=pd.Timedelta('1s'), limit=1)
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 347, in wrapper
>     return func(*args, **kwargs)
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/pandas/core/frame.py", line 5205, in reindex
>     return super().reindex(**kwargs)
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/pandas/core/generic.py", line 5289, in reindex
>     return self._reindex_axes(
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/pandas/core/frame.py", line 5004, in _reindex_axes
>     frame = frame._reindex_index(
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/pandas/core/frame.py", line 5020, in _reindex_index
>     new_index, indexer = self.index.reindex(
>   File "/home/chris/influx-testing/.venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4419, in reindex
>     raise ValueError(
> ValueError: cannot reindex a non-unique index with a method or limit

**Comment by smallsr** [comment]
Hi @chriszal. Would you be able to send over an example csv with the issue to see if we can replicate the error?

**Comment by chriszal** [comment]
[source.csv](https://github.com/OxWearables/stepcount/files/11856332/source.csv)
@smallsr hey thats the one i tried to use.

**Comment by smallsr** [comment]
@chriszal This fails for me too. I'll play around with it more and see what I can find. Perhaps @chanshing 's keen eye will spot something as well.

**Comment by chriszal** [comment]
maybe it's an issue with my timestamps?

**Comment by chanshing** [comment]
The error seems to suggest there are duplicate timestamps. I'll look into it today.

**Comment by chanshing** [comment]
Hi @chriszal it should be fixed now in v2.1.6
Update with `$ pip install -U stepcount`
For your specific file, this is the output:

![image](https://github.com/OxWearables/stepcount/assets/5551642/daac5fff-1f4f-4ce0-acdd-92e5e78209e5)

If you don't mind, what device is this? Is it wrist-worn?

**Comment by chriszal** [comment]
Okay thanks a lot! I was using an android's device sensor. I knew the model wouldn't really work because it's not a wrist-worn device, I just wanted to test it out.
