### ISSUE TITLE
Error Running Stepcount in Pycharm

### ISSUE THREAD

**Issue by dannylvn** [OxWearables/stepcount#27]
I am trying to run stepcount using PyCharm

Following your instructions on processing multiple files on windows https://github.com/OxWearables/stepcount#windows
I have a file commands.txt with 2 cwa files sample1 & sample2 :   
stepcount sample1.cwa &
stepcount sample2.cwa 
:END

On processing com < commands,txt   get the following error:  

C:\Users\dlevin>cmd < commands.txt
Microsoft Windows [Version 10.0.17763.4377]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\dlevin>stepcount sample1.cwa &
'stepcount' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\dlevin>stepcount sample2.cwa
'stepcount' is not recognized as an internal or external command,
operable program or batch file.

Any ideas how to solve this?

**Comment by smallsr** [comment]
Hi @dannylvn. Thanks for using stepcount. I'll copy @chanshing in this as well. It seems like the file is running in a directory or virtual environment that stepcount is not installed in. Are you able to get a single file to run within the dlevin directory, but not multiple files?

**Comment by chanshing** [comment]
@dannylvn It looks like stepcount is not getting picked up by the environment in which you're running the commands. It is difficult for me to debug this as I don't use PyCharm. @angerhang Do you happen to know?

**Comment by dannylvn** [comment]
Thankyou both for responding.
It is happening with a single file as well:

1.	Installed the stepcount package  (screenshots Capture1 & Capture2  attached)
2.	Have file sample2.cwa   in C:\Users\dlevin   (Capture3) 
3.	On trying to run stepcount with command   >  py -m stepcount sample2.cwa     get error msg:
        “No module named stepcount.__main__; 'stepcount' is a package and cannot be directly executed”    (screenshot Capture4)

![Capture1](https://github.com/OxWearables/stepcount/assets/137424774/9590bf44-8384-46d8-8df7-82246e6530f7)
![Capture2](https://github.com/OxWearables/stepcount/assets/137424774/903e454d-29da-411d-b780-339c24026119)
![Capture3](https://github.com/OxWearables/stepcount/assets/137424774/4417bfb0-7401-4105-bd0d-348e1cd6c8bd)
![Capture4](https://github.com/OxWearables/stepcount/assets/137424774/44224fcc-2141-4d51-8253-a5fb48bc6154)

**Comment by chanshing** [comment]
@dannylvn 
Oh, you need to run it like this:

```console
$ stepcount sample2.cwa
```

**Comment by dannylvn** [comment]
No.  That's the syntax for terminal runs in pycharm.
Note the different error msg  for    > stepcount sample2.cwa 

![Capture1](https://github.com/OxWearables/stepcount/assets/137424774/9227e7d4-843a-4e67-8433-0ee504c60539)

![Capture2](https://github.com/OxWearables/stepcount/assets/137424774/0686c3c1-4908-4130-a9f8-d97830ba382c)

**Comment by dannylvn** [comment]
py -c "import stepcount; print(stepcount.__version__)"   works
Returns:   2.1.5

![Capture](https://github.com/OxWearables/stepcount/assets/137424774/3ef9676c-f449-4a44-9d79-1d504a2598ed)

**Comment by chanshing** [comment]
Ah I see. Thanks. 
Can you try `py -m stepcount.stepcount sample2.cwa` ?

**Comment by dannylvn** [comment]
That syntax seems to work.
but getting error now:

_Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python310\lib\runpy.py", line 157, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\dlevin\AppData\Roaming\Python\Python310\site-packages\stepcount\stepcount.py", line 368
    sn    main()
    ^
IndentationError: expected an indented block after 'if' statement on line 367_

![Capture](https://github.com/OxWearables/stepcount/assets/137424774/ff014b20-76b2-44d4-83dd-0c213067ea70)

**Comment by dannylvn** [comment]
see below.  (file has 368 lines)

![Capture](https://github.com/OxWearables/stepcount/assets/137424774/ebd53395-dbf6-45c5-bb30-74b08f5a0fbf)

**Comment by chanshing** [comment]
Do you know how those two "sn" letters ended up there in line 368? That is not part of the package.

https://github.com/OxWearables/stepcount/blob/134078068486fec87ff89ffce817129ff7c5ca4b/src/stepcount/stepcount.py#L368

**Comment by chanshing** [comment]
Can you try the following:

1. Set your Windows PATH:
```console
$ SET PATH=%PATH%C:\Users\dlevin\AppData\Roaming\Python\Python310\Scripts
```
2. Run `stepcount` without `py -m`:
```console
$ stepcount sample1.cwa
```

**Comment by dannylvn** [comment]
That fixed it.  Thank you so much!  sorry for all the bother.

**Comment by chanshing** [comment]
@dannylvn Great! Not at all. We're glad to help!
