### ISSUE TITLE
Facing Issues with CSV Files

### ISSUE THREAD

**Issue by SrinivasChoudhury** [OxWearables/stepcount#45]
Facing lot many Issues with CSV Files. May be I missing something or running wrongly.

My CSV files are as below.

**sample1.csv**
time,x,y,z
2013-03-01 15:15:01.010,-1,65,5
2013-03-01 15:15:01.020,-1,65,5
2013-03-01 15:15:01.030,-1,65,4
2013-03-01 15:15:01.040,-1,65,5
2013-03-01 15:15:01.050,-1,64,5
2013-03-01 15:15:01.060,-1,64,5
2013-03-01 15:15:01.070,-1,65,5
2013-03-01 15:15:01.080,-1,65,4
2013-03-01 15:15:01.090,-1,65,5

**sample2.csv**
time,x,y,z
1683684921,34.0,-5.0,54.0
1683684922,34.0,-5.0,55.0
1683684923,33.0,-5.0,55.0
1683684924,34.0,-5.0,54.0
1683684925,34.0,-5.0,55.0
1683684926,33.0,-5.0,55.0
1683684927,34.0,-5.0,55.0
1683684928,33.0,-5.0,55.0
1683684929,33.0,-5.0,55.0
1683684910,34.0,-4.0,55.0
1683684911,34.0,-4.0,55.0
1683684912,33.0,-5.0,55.0
1683684913,34.0,-5.0,55.0
1683684914,34.0,-5.0,55.0
1683684915,33.0,-5.0,55.0
1683684916,33.0,-5.0,54.0
1683684917,34.0,-5.0,54.0

As I am exploring this as a beginner, it would be great if someone can give sample CSV data, notes and any example/article/video with CSV.

Thanks In Advance.

**Comment by chanshing** [comment]
Can you share the error messages that you are getting?

**Comment by SrinivasChoudhury** [comment]
When I run with above sample1.csv, I get below error message.
![image](https://github.com/OxWearables/stepcount/assets/19350520/2f61770b-ba3b-4883-8042-0275d90788df)

When I run with above sample2.csv, I get below error message.
![image](https://github.com/OxWearables/stepcount/assets/19350520/50b001c8-90a4-46ff-9d42-11c2706bada8)

**Comment by chanshing** [comment]
This is fixed now in `actipy==3.0.4` (`actipy` is a dependency in `stepcount`)
Please run `pip install -U actipy` to get the latest version.
